version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - INTAKE_API_URL=http://backend:8000/api/intake
      - NEXT_PUBLIC_CONN_DETAILS_ENDPOINT=/api/connection-details
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: pnpm dev

  backend:
    build:
      context: ./voice_agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./voice_agent:/app
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python main.py
